# Generated by Django 2.2.1 on 2019-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/image.jpg', upload_to='images/'),
        ),
    ]
